# Form implementation generated from reading ui file 'c:\Users\Acer\Desktop\PTI\ui\Home.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 588)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widget.setStyleSheet("background-color:rgb(233, 255, 255);\n"
"border-color: rgb(152, 255, 255);")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.b0 = QtWidgets.QPushButton(parent=self.widget)
        self.b0.setStyleSheet("border: 2 rgb(0, 170, 255);")
        self.b0.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Acer\\Desktop\\PTI\\ui\\../img/joystick.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b0.setIcon(icon)
        self.b0.setIconSize(QtCore.QSize(50, 50))
        self.b0.setObjectName("b0")
        self.verticalLayout.addWidget(self.b0)
        self.b1 = QtWidgets.QPushButton(parent=self.widget)
        self.b1.setStyleSheet("border: 2 rgb(0, 170, 255);")
        self.b1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Acer\\Desktop\\PTI\\ui\\../img/cpu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b1.setIcon(icon1)
        self.b1.setIconSize(QtCore.QSize(50, 50))
        self.b1.setObjectName("b1")
        self.verticalLayout.addWidget(self.b1)
        self.b2 = QtWidgets.QPushButton(parent=self.widget)
        self.b2.setStyleSheet("border: 2 rgb(0, 170, 255);")
        self.b2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Acer\\Desktop\\PTI\\ui\\../img/magnifier.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.b2.setIcon(icon2)
        self.b2.setIconSize(QtCore.QSize(50, 50))
        self.b2.setObjectName("b2")
        self.verticalLayout.addWidget(self.b2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.listWidget = QtWidgets.QListWidget(parent=self.widget_2)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "modify"))
        self.pushButton_2.setText(_translate("MainWindow", "delete"))
        self.pushButton.setText(_translate("MainWindow", "add"))
        self.pushButton_4.setText(_translate("MainWindow", "sort"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "search"))
