# Form implementation generated from reading ui file 'c:\Users\Acer\Desktop\PTI\ui\signup.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(217, 211)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.p0 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.p0.setStyleSheet("border-radius:5px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.p0.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.p0.setObjectName("p0")
        self.gridLayout.addWidget(self.p0, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.n0 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.n0.setStyleSheet("border-radius:5px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.n0.setObjectName("n0")
        self.gridLayout.addWidget(self.n0, 1, 1, 1, 1)
        self.press0 = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press0.setFont(font)
        self.press0.setStyleSheet("border-radius:5px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.press0.setObjectName("press0")
        self.gridLayout.addWidget(self.press0, 4, 1, 1, 1)
        self.press1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.press1.setStyleSheet("border-radius:5px;\\nborder-color: rgb(255, 255, 255);\\nbackground-color: rgb(255, 255, 255);")
        self.press1.setObjectName("press1")
        self.gridLayout.addWidget(self.press1, 6, 1, 1, 1)
        self.p1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.p1.setStyleSheet("border-radius:5px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.p1.setText("")
        self.p1.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.p1.setObjectName("p1")
        self.gridLayout.addWidget(self.p1, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setStyleSheet("border-radius:5px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Signup"))
        self.p0.setPlaceholderText(_translate("MainWindow", "Password"))
        self.n0.setPlaceholderText(_translate("MainWindow", "Name"))
        self.press0.setText(_translate("MainWindow", "Signup"))
        self.press1.setText(_translate("MainWindow", "To Login"))
        self.p1.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.pushButton.setText(_translate("MainWindow", "Save Face"))
